[package]
name = "momoden-password-calc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
arrayvec = "0.7.2"
int-enum = "0.5.0"
seed = "0.9.2"

momoden-password = "0.1.0"
